version: 2

models:
  - name: registration_record_partnership
    description: "Productiojn data of the registration records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: training_record_partnership
    description: "Production data of the training records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: event_record_partnership
    description: "Production data of the event records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - not_null

  - name: meeting_record_partnership
    description: "Production data of the meeting records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - not_null

  - name: interaction_record_partnership
    description: "Production data of the interaction records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - not_null

  - name: cl_civic_action_partnership
    description: "Production data of the Community level civic action records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - not_null

  - name: hl_civic_action_partnership
    description: "Production data of the Household Level Civic Action records for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - not_null

  - name: stakeholder_visit_record_partnership
    description: "Production data of the Stakeholder Visits for partnership" 
    +schema: production
    columns: 
       - name: id
         description: "The primary key for this table"
         tests:
           - not_null